package main

class WordArrays {
   companion object{
       var easyArray = arrayOf(
       "Application",
       "Motorola",
       "Package",
       "India",
       "Water",
       "Bottle",
       "Random",
       "Medicine",
       "Six",
       "Games",
       "Wasteful",
       "Play" ,
       "Fork",
       "Switch",
       "Legs",
       "Selective",
       "Print",
       "Nifty",
       "Violent",
       "Meddle",
       "Preach",
       "Bulking",
       "Java",
       "Kotlin"
       )
       var mediumArray = arrayOf(
           "Bresenham",
           "Scissors",
           "Quinoa",
           "Callous",
           "Independence",
           "Unambiguous",
           "Quiet",
           "Quite",
           "Exaggeration",
           "Introspection",
           "Toys",
           "Toothbrush",
           "Wind",
           "Science",
           "Accessible",
           "Signal",
           "Cut",
           "Guide",
           "Book",
           "Jewel",
           "Extra",
           "Shrug",
           "Articulation",
           "Circulation"
       )
       var hardArray = arrayOf(
           "Pellucid",
           "Indoctrination",
           "Gratuitous",
           "Egregious",
           "Circumlocution",
           "Equivocate",
           "Curmudgeon",
           "Surreptitious",
           "Puissant",
           "Solicitous",
           "Lamentable",
           "Condemned",
           "Placid",
           "Momentous",
           "Chipmunk",
           "Gratitude",
           "Pollination",
           "Armageddon",
           "Intoxication",
           "Circumference",
           "Croissant",
           "Solitude",
           "Equilibrium",
           "Amalgamation",
           "Generation"
       )
   }
}